version: 2.1

orbs:
  node: circleci/node@1.0.1

jobs:
  build:
    executor:
      name: node/default
      tag: '10'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install dependency
                command: yarn install
          dir: ~/.cache/yarn
          cache-key: yarn.lock
      - run:
          name: Build site
          command: yarn workspace frontend generate:ropsten
      - persist_to_workspace:
          root: .
          paths:
              - ./frontend/dist
  deploy:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "b5:9a:5e:4d:d0:0a:65:28:45:f8:46:24:d5:b0:54:b5"
      - run:
          name: initialize git
          command: |
            git init .
            git config --global user.name "odan"
            git config --global user.email "odan3240@gmail.com"
          working_directory: ./frontend/dist
      - run:
          name: deploy to gh-pages
          command: |
            git checkout -b gh-pages
            git add ./
            git commit -m 'Update [ci skip]'
            git push -f git@github.com:odanado/ethereum-message-sandbox.git gh-pages
          working_directory: ./frontend/dist

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires: [build]
          filters:
            branches:
              only: master
