version: 2.1

orbs:
  node: circleci/node@1.0.1

jobs:
  build:
    executor:
      name: node/default
      tag: '10'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install dependency
                command: yarn install
          dir: ~/.cache/yarn
          cache-key: yarn.lock
      - run:
          name: Build contract
          command: yarn workspace ethereum build
      - run:
          name: Build site
          command: yarn workspace frontend generate:ropsten
      - persist_to_workspace:
          root: .
          paths:
              - ./frontend/dist
              - ./bin
  deploy:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "b5:9a:5e:4d:d0:0a:65:28:45:f8:46:24:d5:b0:54:b5"
      - run:
          name: Deploy
          command: ./bin/deploy.sh

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires: [ build ]
          filters:
            branches:
              only: master
